# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f3871afec5d155ab47aa1aa653ecfed69adc4e5a0c3686d7cad7aff73b44f701ec57ec05b142497fb8c35b4060b9cc1e2c0828e04d106c2e0fb4ec9378a83d

test:
  secret_key_base: 84596f3541877769efdc4ea57446c9590ae1095acf4ff790550b694ad89251d042fd533f52b3b3e67ab8b4c97189abfbb2bc0884f9ffe2f4d98ed3ecb92b9752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
